name: Deploy Documentation
# This workflow deploys the Jupyter Book documentation to GitHub Pages.
# See here for more information:
# https://jupyterbook.org/stable/build-and-publish/website/
# https://jupyterbook.org/v1/publish/gh-pages.html

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    # Required to deploy to GitHub Pages since docs are in a subfolder
    env:
      BASE_URL: /${{ github.event.repository.name }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip

      - name: Install dependencies
        run: pip install -e ".[docs]"

      # Build the book
      - name: Build the book
        run: |
          jupyter book build --html

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _build/html

      # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
